library(gnorm)
library(rTensor)
library(RcppHungarian)
library(ggplot2)
library(reshape2) # melt() function
library(ggnewscale) # geom_raster() in ggplot, figure 7.
library(fICA)
library(JADE) # figure 6
## There is no explicit explanation how fICA choose initial estimate but 
## adapt_fICA, a function included in the same package "fICA" use (FOBI or k-JADE) estimator
## as initial estimate.
# library(fastICA)


gen_trueW <- function(d){
    W = diag(rep(1, d))
    if (d > 1){
        for (j in 1:(d-1)){
            W[j, j+1] = -.5
            W[j+1, j] = .5
        }
    }
    return(W)
}

hard_thre <- function(w,lambda){
    w[abs(w) <= lambda] = 0
    w[abs(w) > lambda] = 1
    return(w)
}

sign_hungarian = function(unwh_trueW,estWu){
    # sign adjustment
    d = dim(unwh_trueW)[1]
    for (i in 1:d){
    ord1 = order(abs(estWu[i, ]))
    ord2 = order(abs(unwh_trueW[i, ]))

    if ( sum(estWu[i,ord1] * unwh_trueW[i,ord2]) < 0 ){
        estWu[i, ] = -estWu[i, ]
        }
    }
    # hungarian matching
    cost = -abs(estWu %*% t(unwh_trueW)) ## cost[j, k] row j of myWu against row k of Wu
    soln = HungarianSolver(cost)
    estWu[soln$pairs[, 2], ] = estWu
    return(estWu)
}

kurt_to_mat = function(mat){
    mat= unfold(mat, row_idx=c(1,2), col_idx=c(3,4))
    mat = mat@data
    return(mat) 
}

gamma_kurt_tensor = function(unwh_trueW){
    true_k = as.tensor(array(0, dim=c(d,d,d,d)))
    for(j in 1:d){
    A = solve(unwh_trueW)
    foo = outer(A[,j],A[,j])
    bar = outer(foo,foo)
    bar = as.tensor(bar)
    true_k = true_k + bar* (6/j)
    }    
    return(true_k)
}

frob_norm = function(trueW,estW){
    distance = sqrt(sum(trueW-estW)^2)
    return(distance)
}

ICA_graph = function(W){
    d = dim(W)[1]
    graph = matrix(0,d,d)
    for(i in 1:d){
        for(j in 1:d){
            b1 = which(W[,i]!=0)
            b2 = which(W[,j]!=0)
            b3 =intersect(b1,b2)
            graph[i,j] = ifelse( length(b3) >0 ,1,0)
        }
    }
    return(graph)
}

Auddy_M0 = function(X){
    M0 = array(0, dim=c(d,d,d,d))
    for (i in 1:d)
    {
        for(j in 1:d)
        {
            for(k in 1:d)
            {
                for(l in 1:d)
                {
                index = c(i,j,k,l)
                uni.index = unique(index)
                if(  length(uni.index) <=2)
                    {
                    M0[i,j,k,l] = 1
                    }              
                }
            }
        }
    }
    out = M0
    return(out)    
}

# Auddy alogorithm 3
Auddy_prewhiten = function(X,trueW){ 
    X = X - matrix(1, nrow(X), 1) %*% apply(X, 2, mean)
    n = dim(X)[1]
    nn= floor(n/2)
    T1 = sample(n,nn)
    X1 = X[T1,]   
    X2 = X[-T1,]
    var.X1 = var(X1)
    res = eigen(var.X1)
    Whitening_mat = (res$vectors) %*% diag(res$values^{-1/2}) %*% t((res$vectors))
    X = X %*% Whitening_mat
    unwh_trueW =  trueW %*% t( solve(Whitening_mat) ) 
    out = list(unwh_trueW=unwh_trueW, X=X, Whitening_mat=Whitening_mat)
    return(out)
}

# Auddy algorithm 2
Auddy_M4hat_pg20 = function(X){
    d = dim(X)[2]
    n = dim(X)[1]
    nn= floor(n/2)
    T1 = sample(n,nn) 
    S1 = X[T1,]   
    S2 = X[-T1,]

    Y1= matrix(0,nn,d^2)
    Y2= matrix(0,(n-nn),d^2)

    for(i in 1:nn){
       Y1[i,] = outer(S1[i,], S1[i,])
    }

    for(i in 1:(n-nn)){
       Y2[i,] = outer(S2[i,], S2[i,])
    } 

    Y1 = Y1 - matrix(1, nrow(Y1), 1) %*% apply(Y1, 2, mean)
    Y2 = Y2 - matrix(1, nrow(Y2), 1) %*% apply(Y2, 2, mean)
    vec_I = c(diag(1,d))

    M1.hat = 1/nrow(Y1) *  t(Y1)%*%(Y1) + vec_I %*% t(vec_I)
    M2.hat = 1/nrow(Y2) *  t(Y2)%*%(Y2) + vec_I %*% t(vec_I)

    M0 = Auddy_M0(X); M0 = as.tensor(M0)
    M0_12_34 = unfold(M0, row_idx= c(1,2), col_idx=c(3,4))@data
    P = M2.hat - M0_12_34
    res = svd(P)
    P_hat = res$u[,1:d]%*% diag( res$d[1:d]) %*% t(res$v[,1:d]) 

    tmp = P_hat %*% (M1.hat- M0_12_34) %*% P_hat
    M_hat = fold(tmp, row_idx= c(1,2), col_idx=c(3,4), modes=c(d,d,d,d))
    # M_hat is 4th cumulant tensor estimate
    return(M_hat)
}

my_m4_hat = function(X){
    d = dim(X)[2]
    n = dim(X)[1]
    M4hat = as.tensor(array(0, dim=c(d,d,d,d)))
    for (i in 1:n){
    foo = outer(X[i, ], X[i, ])
    bar = outer(foo, foo)
    bar = as.tensor(bar)
    M4hat = M4hat + bar
    }
    M4hat = (1/n)*M4hat

    M0 = array(0, dim=c(d,d,d,d))
    for (i in 1:d){
        for (j in 1:d){
             for (k in 1:d){
                 for (l in 1:d){
                 index = c(i,j,k,l)
                 uni.index = unique(index)
                 temp = as.matrix(table(index))
                 if(  length(uni.index)==1) ## i=j=k=l
                    M0[i,j,k,l] = 3
                 else if (temp[1]==temp[2] & length(uni.index)==2) ## {i,j,k,l}= {i1,i2}, i1 \neq i2
                    M0[i,j,k,l] = 1
                }
            }
        }
    }
    out = M4hat - M0
    return(out)
}

## random slicing
Auddy_init_u = function(X,Mhat,L){
    top.s.list = rep(0,L)
    top.u.list = list()
    for (l in 1:L){
        G = matrix(rnorm(d^2),d,d)    
        mat = matrix(0,d,d)
        for(i in 1:d){
            for(j in 1:d){
                mat[i,j] = sum(diag(Mhat[,,i,j]@data %*%G)) # matrix(Mhat[,,i,j]@data,1,d^2) %*% matrix(G,d^2,1)
            }
        }
        res = svd(mat)
        top.s.list[l] = res$d[1]
        top.u.list[[l]] = res$u[,1]
    }
    ind = order(top.s.list, decreasing=TRUE)
    ul.star = top.u.list[[ ind[1] ]] 
    return(ul.star)
}

## Auddy m4hat Auddy deflation
Auddy_fastICA = function(X,unwh_trueW,L,T){
    W = matrix(0, d,d)
    n = nrow(X)
    for (j in 1:d){   
        Mhat = Auddy_M4hat_pg20(X)
        a_j = c(Auddy_init_u(X,Mhat,L))
        for(t in 1:T){
            a_j = a_j - 1/(3*n) *t(X) %*% (X %*% a_j)^3   
            a_j = a_j/ norm(a_j,"2")            
        }   
        for(i in 1:n){
            X[i,] = X[i,] - as.numeric( t(a_j) %*% X[i,] )*a_j
        }
        W[j,] = a_j
    }
    W = sign_hungarian(unwh_trueW,W)
    return(W)
}

#######################
#######################

## my_m4hat and my deflation (Algorithm 1)

Auddy_fastICA_mod2 = function(X,unwh_trueW,L,T){
    d = dim(X)[2]
    W = matrix(0, d,d)
    n = nrow(X)
    Mhat = my_m4_hat(X)
    for (j in 1:d){
        a_j = c(Auddy_init_u(X,Mhat,L))
        a_j_old = a_j
        for(t in 1:T){
            a_j = a_j_old - 1/(3*n) *t(X) %*% (X %*% a_j)^3   
        
            if (j>1){
            sum = rep(0,d)
                for(k in 1:(j-1)){
                sum = sum + as.numeric(t(a_j) %*% W[k,]) * W[k,] 
                }
            a_j = a_j - sum
            } 
        a_j = a_j/ norm(a_j,"2")            
        }   
        W[j,] = a_j
    }
    W = sign_hungarian(unwh_trueW,W)
    return(W)
}

#########################
#########################

## my_m4hat and Auddy deflation
Auddy_fastICA_mod3 = function(X,unwh_trueW,L,T){
    W = matrix(0, d,d)
    n = nrow(X)
    for (j in 1:d){
        Mhat = my_m4_hat(X)
        a_j = c(Auddy_init_u(X,Mhat,L))
        a_j_old = a_j
        for(t in 1:T){
            a_j = a_j_old - 1/(3*n) *t(X) %*% (X %*% a_j)^3   
            a_j = a_j/ norm(a_j,"2")           
        }   
        for(i in 1:n){
            X[i,] = X[i,] -   as.numeric( t(a_j) %*% X[i,] )*a_j
        }
        W[j,] = a_j
    }
    W = sign_hungarian(unwh_trueW,W)
    return(W)
}
##########################
##########################

## Auddy m4hat my deflation
Auddy_fastICA_mod4 = function(X,unwh_trueW,L,T){
    W = matrix(0, d,d)
    n = nrow(X)
    Mhat = Auddy_M4hat_pg20(X)
    for (j in 1:d){
        a_j = c(Auddy_init_u(X,Mhat,L))
        a_j_old = a_j
        for(t in 1:T){
            a_j = a_j_old - 1/(3*n) *t(X) %*% (X %*% a_j)^3   
        
            if (j>1){
            sum = rep(0,d)
                for(k in 1:(j-1)){
                sum = sum + as.numeric(t(a_j) %*% W[k,]) * W[k,] 
                }
            a_j = a_j - sum
            } 
        a_j = a_j/ norm(a_j,"2")            
        }   
        W[j,] = a_j
    }
    W = sign_hungarian(unwh_trueW,W)
    return(W)
}

############################################
############################################
my_m4_hat2 = function(X){  
    n = nrow(X)
    nn= floor(n/2)
    T1 = sample(n,nn) 
    S1 = X[T1,]   
    S2 = X[-T1,]
    Y1= matrix(0,nn,d^2)
    Y2= matrix(0,(n-nn),d^2)

    for(i in 1:nn){
       Y1[i,] = outer(S1[i,], S1[i,])
    }

    for(i in 1:(n-nn)){
       Y2[i,] = outer(S2[i,], S2[i,])
    } 
    Y1 = Y1 - matrix(1, nrow(Y1), 1) %*% apply(Y1, 2, mean)
    Y2 = Y2 - matrix(1, nrow(Y2), 1) %*% apply(Y2, 2, mean)
    vec_I = c(diag(1,d))
    M1.hat = 1/nrow(Y1) *  t(Y1)%*%(Y1) + vec_I %*% t(vec_I)
    M2.hat = 1/nrow(Y2) *  t(Y2)%*%(Y2) + vec_I %*% t(vec_I)

    M0 = array(0, dim=c(d,d,d,d))
    for (i in 1:d){
        for (j in 1:d){
             for (k in 1:d){
                 for (l in 1:d){
                 index = c(i,j,k,l)
                 uni.index = unique(index)
                 temp = as.matrix(table(index))
                 if(  length(uni.index)==1) ## i=j=k=l
                    M0[i,j,k,l] = 3
                 else if (temp[1]==temp[2] & length(uni.index)==2) ## {i,j,k,l}= {i1,i2}, i1 \neq i2
                    M0[i,j,k,l] = 1
                }
            }
        }
    }

    M0 = as.tensor(M0)
    M0_12_34 = unfold(M0, row_idx= c(1,2), col_idx=c(3,4))@data
    P = M2.hat - M0_12_34
    res = svd(P)
    P_hat = res$u[,1:d]%*% diag( res$d[1:d]^{1}) %*% t(res$v[,1:d]) ## diff
    P_hat2 = res$u[,1:d]%*% diag( res$d[1:d]^{-1}) %*% t(res$v[,1:d]) ## diff

    tmp = P_hat %*% (M1.hat- M0_12_34) %*% P_hat
    M_hat = fold(tmp, row_idx= c(1,2), col_idx=c(3,4), modes=c(d,d,d,d))
    return(M_hat)
}

## (Auddy 4th moment + my m0) and my deflation
Auddy_fastICA_mod5 = function(X,unwh_trueW,L,T){
    W = matrix(0, d,d)
    n = nrow(X)
    Mhat = my_m4_hat2(X)
    for (j in 1:d){
        a_j = c(Auddy_init_u(X,Mhat,L))
        a_j_old = a_j
        for(t in 1:T){
            a_j = a_j_old - 1/(3*n) *t(X) %*% (X %*% a_j)^3   
        
            if (j>1){
            sum = rep(0,d)
                for(k in 1:(j-1)){
                sum = sum + as.numeric(t(a_j) %*% W[k,]) * W[k,] 
                }
            a_j = a_j - sum
            } 
        a_j = a_j/ norm(a_j,"2")            
        }   
        W[j,] = a_j
    }
    W = sign_hungarian(unwh_trueW,W)
    return(W)
}



